### ISSUE TITLE
Use a static name/url for latest csv

### ISSUE THREAD

**Issue by rexdouglass** [microsoft/Bing-COVID-19-Data#3]
The latest csv is named with a date and the old one is taken down "2020-4-23.csv"

More helpful would be "bing_covid_latest.csv" possibly alongside a dated file. That would provide a static url to target to always grab the latest data.

**Comment by OnArs** [comment]
I double on this. Could it be implemented?

**Comment by c-don** [comment]
thats a good suggestion. we will look to change the filename shortly.

**Comment by chiqunz** [comment]
We have changed the file name to "Bing-COVID19-Data.csv'. Update history could be find through github commit history. Thanks!
