### ISSUE TITLE
Daily data updates ceased on 11/25/2020

### ISSUE THREAD

**Issue by goodtocode** [microsoft/Bing-COVID-19-Data#47]
Hi all,

The daily commits have ceased and the data is of course not refreshed. If this repo is no longer maintained, any way we can open source the aggregation and hosting? This data will be critical for business decisions for months/years to come.

Thanks Bing Team!
Robert

**Comment by goodtocode** [comment]
Received a reply from the Bing COVID-19 Team and they are investigating. Cant thank Microsoft and Bing enough for maintaining this data!

**Comment by paulogs** [comment]
That is great news, thanks for the update.

**Comment by goodtocode** [comment]
The data resumed on 12/10/2020, closing issue. Thank you to the Bing covid team!

**Comment by rangelsfr** [comment]
[link my bank account ]()
