### ISSUE TITLE
How to access the data? 

### ISSUE THREAD

**Issue by AaronWard** [microsoft/Bing-COVID-19-Data#7]
> **Can I access the COVID-19 data?**
>Yes! Check out the Bing COVID-19 data on GitHub

Can someone point me in the right direction on how to get the data because i can't find it?

Thank you in advance @chiqunz

**Comment by PhArraes** [comment]
The csv was deleted today,
we can still access yesterday data.
[commit may 6](https://github.com/microsoft/Bing-COVID-19-Data/tree/433b8b0900d946a020df35f85db013509b6c6b5f/data)
Will we still have access to the data?
